name: C++26 Build with Clang

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-17

      - name: Configure with Clang
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++-17

      - name: Build
        run: cmake --build build

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator
          path: build/calculator
